// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: SMD.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_SMD_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{0}
}

func (x *PingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingReply) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_SMD_proto protoreflect.FileDescriptor

const file_SMD_proto_rawDesc = "" +
	"\n" +
	"\tSMD.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\tPingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2K\n" +
	"\x17ServiceDiscoveryManager\x120\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x0e.api.PingReply\"\x00B0Z.github.com/richardbaah/RouteFinder/src/api;apib\x06proto3"

var (
	file_SMD_proto_rawDescOnce sync.Once
	file_SMD_proto_rawDescData []byte
)

func file_SMD_proto_rawDescGZIP() []byte {
	file_SMD_proto_rawDescOnce.Do(func() {
		file_SMD_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SMD_proto_rawDesc), len(file_SMD_proto_rawDesc)))
	})
	return file_SMD_proto_rawDescData
}

var file_SMD_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SMD_proto_goTypes = []any{
	(*PingReply)(nil),             // 0: api.PingReply
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_SMD_proto_depIdxs = []int32{
	1, // 0: api.PingReply.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: api.ServiceDiscoveryManager.Ping:input_type -> google.protobuf.Empty
	0, // 2: api.ServiceDiscoveryManager.Ping:output_type -> api.PingReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SMD_proto_init() }
func file_SMD_proto_init() {
	if File_SMD_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SMD_proto_rawDesc), len(file_SMD_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_SMD_proto_goTypes,
		DependencyIndexes: file_SMD_proto_depIdxs,
		MessageInfos:      file_SMD_proto_msgTypes,
	}.Build()
	File_SMD_proto = out.File
	file_SMD_proto_goTypes = nil
	file_SMD_proto_depIdxs = nil
}
