// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: SMD.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadBalance int32

const (
	LoadBalance_LOAD_BALANCE_NONE        LoadBalance = 0
	LoadBalance_LOAD_BALANCE_ROUND_ROBIN LoadBalance = 1
	LoadBalance_LOAD_BALANCE_URL_HASH    LoadBalance = 2
	LoadBalance_LOAD_BALANCE_RANDOM      LoadBalance = 3
)

// Enum value maps for LoadBalance.
var (
	LoadBalance_name = map[int32]string{
		0: "LOAD_BALANCE_NONE",
		1: "LOAD_BALANCE_ROUND_ROBIN",
		2: "LOAD_BALANCE_URL_HASH",
		3: "LOAD_BALANCE_RANDOM",
	}
	LoadBalance_value = map[string]int32{
		"LOAD_BALANCE_NONE":        0,
		"LOAD_BALANCE_ROUND_ROBIN": 1,
		"LOAD_BALANCE_URL_HASH":    2,
		"LOAD_BALANCE_RANDOM":      3,
	}
)

func (x LoadBalance) Enum() *LoadBalance {
	p := new(LoadBalance)
	*p = x
	return p
}

func (x LoadBalance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalance) Descriptor() protoreflect.EnumDescriptor {
	return file_SMD_proto_enumTypes[0].Descriptor()
}

func (LoadBalance) Type() protoreflect.EnumType {
	return &file_SMD_proto_enumTypes[0]
}

func (x LoadBalance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalance.Descriptor instead.
func (LoadBalance) EnumDescriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{0}
}

type HeartBeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	mi := &file_SMD_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{0}
}

func (x *HeartBeatRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_SMD_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingReply) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Endpoints     []*ServiceEndpoint     `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Algo          LoadBalance            `protobuf:"varint,3,opt,name=algo,proto3,enum=api.LoadBalance" json:"algo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_SMD_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterServiceRequest) GetEndpoints() []*ServiceEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *RegisterServiceRequest) GetAlgo() LoadBalance {
	if x != nil {
		return x.Algo
	}
	return LoadBalance_LOAD_BALANCE_NONE
}

type AddInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Endpoints     []*ServiceEndpoint     `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInstanceRequest) Reset() {
	*x = AddInstanceRequest{}
	mi := &file_SMD_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInstanceRequest) ProtoMessage() {}

func (x *AddInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInstanceRequest.ProtoReflect.Descriptor instead.
func (*AddInstanceRequest) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{3}
}

func (x *AddInstanceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AddInstanceRequest) GetEndpoints() []*ServiceEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCode   int32                  `protobuf:"varint,1,opt,name=successCode,proto3" json:"successCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_SMD_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{4}
}

func (x *GenericResponse) GetSuccessCode() int32 {
	if x != nil {
		return x.SuccessCode
	}
	return 0
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServiceEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IP            string                 `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEndpoint) Reset() {
	*x = ServiceEndpoint{}
	mi := &file_SMD_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEndpoint) ProtoMessage() {}

func (x *ServiceEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEndpoint.ProtoReflect.Descriptor instead.
func (*ServiceEndpoint) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceEndpoint) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *ServiceEndpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_SMD_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{6}
}

func (x *Service) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ResolveServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*ServiceEndpoint     `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveServiceResponse) Reset() {
	*x = ResolveServiceResponse{}
	mi := &file_SMD_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveServiceResponse) ProtoMessage() {}

func (x *ResolveServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveServiceResponse.ProtoReflect.Descriptor instead.
func (*ResolveServiceResponse) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveServiceResponse) GetEndpoints() []*ServiceEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ResolveMany   bool                   `protobuf:"varint,2,opt,name=resolveMany,proto3" json:"resolveMany,omitempty"` // if true return all endpoints else return one based on load balancing algo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_SMD_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ResolveRequest) GetResolveMany() bool {
	if x != nil {
		return x.ResolveMany
	}
	return false
}

type RenameServiceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OldServiceName string                 `protobuf:"bytes,1,opt,name=old_service_name,json=oldServiceName,proto3" json:"old_service_name,omitempty"`
	NewServiceName string                 `protobuf:"bytes,2,opt,name=new_service_name,json=newServiceName,proto3" json:"new_service_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenameServiceRequest) Reset() {
	*x = RenameServiceRequest{}
	mi := &file_SMD_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameServiceRequest) ProtoMessage() {}

func (x *RenameServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameServiceRequest.ProtoReflect.Descriptor instead.
func (*RenameServiceRequest) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{9}
}

func (x *RenameServiceRequest) GetOldServiceName() string {
	if x != nil {
		return x.OldServiceName
	}
	return ""
}

func (x *RenameServiceRequest) GetNewServiceName() string {
	if x != nil {
		return x.NewServiceName
	}
	return ""
}

// returns all services and their endpoints and load balancing algo
type MetricsResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Services      []*MetricsResponseServiceMetric `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_SMD_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{10}
}

func (x *MetricsResponse) GetServices() []*MetricsResponseServiceMetric {
	if x != nil {
		return x.Services
	}
	return nil
}

type MetricsResponseServiceMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	NumEndpoints  int32                  `protobuf:"varint,2,opt,name=num_endpoints,json=numEndpoints,proto3" json:"num_endpoints,omitempty"`
	Algo          LoadBalance            `protobuf:"varint,3,opt,name=algo,proto3,enum=api.LoadBalance" json:"algo,omitempty"`
	Endpoints     []*ServiceEndpoint     `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponseServiceMetric) Reset() {
	*x = MetricsResponseServiceMetric{}
	mi := &file_SMD_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponseServiceMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponseServiceMetric) ProtoMessage() {}

func (x *MetricsResponseServiceMetric) ProtoReflect() protoreflect.Message {
	mi := &file_SMD_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponseServiceMetric.ProtoReflect.Descriptor instead.
func (*MetricsResponseServiceMetric) Descriptor() ([]byte, []int) {
	return file_SMD_proto_rawDescGZIP(), []int{10, 0}
}

func (x *MetricsResponseServiceMetric) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MetricsResponseServiceMetric) GetNumEndpoints() int32 {
	if x != nil {
		return x.NumEndpoints
	}
	return 0
}

func (x *MetricsResponseServiceMetric) GetAlgo() LoadBalance {
	if x != nil {
		return x.Algo
	}
	return LoadBalance_LOAD_BALANCE_NONE
}

func (x *MetricsResponseServiceMetric) GetEndpoints() []*ServiceEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

var File_SMD_proto protoreflect.FileDescriptor

const file_SMD_proto_rawDesc = "" +
	"\n" +
	"\tSMD.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n" +
	"\x10HeartBeatRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"_\n" +
	"\tPingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x95\x01\n" +
	"\x16RegisterServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x122\n" +
	"\tendpoints\x18\x02 \x03(\v2\x14.api.ServiceEndpointR\tendpoints\x12$\n" +
	"\x04algo\x18\x03 \x01(\x0e2\x10.api.LoadBalanceR\x04algo\"k\n" +
	"\x12AddInstanceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x122\n" +
	"\tendpoints\x18\x02 \x03(\v2\x14.api.ServiceEndpointR\tendpoints\"M\n" +
	"\x0fGenericResponse\x12 \n" +
	"\vsuccessCode\x18\x01 \x01(\x05R\vsuccessCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x0fServiceEndpoint\x12\x0e\n" +
	"\x02IP\x18\x01 \x01(\tR\x02IP\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\",\n" +
	"\aService\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"L\n" +
	"\x16ResolveServiceResponse\x122\n" +
	"\tendpoints\x18\x01 \x03(\v2\x14.api.ServiceEndpointR\tendpoints\"U\n" +
	"\x0eResolveRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12 \n" +
	"\vresolveMany\x18\x02 \x01(\bR\vresolveMany\"j\n" +
	"\x14RenameServiceRequest\x12(\n" +
	"\x10old_service_name\x18\x01 \x01(\tR\x0eoldServiceName\x12(\n" +
	"\x10new_service_name\x18\x02 \x01(\tR\x0enewServiceName\"\x85\x02\n" +
	"\x0fMetricsResponse\x12>\n" +
	"\bservices\x18\x01 \x03(\v2\".api.MetricsResponse.serviceMetricR\bservices\x1a\xb1\x01\n" +
	"\rserviceMetric\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12#\n" +
	"\rnum_endpoints\x18\x02 \x01(\x05R\fnumEndpoints\x12$\n" +
	"\x04algo\x18\x03 \x01(\x0e2\x10.api.LoadBalanceR\x04algo\x122\n" +
	"\tendpoints\x18\x04 \x03(\v2\x14.api.ServiceEndpointR\tendpoints*v\n" +
	"\vLoadBalance\x12\x15\n" +
	"\x11LOAD_BALANCE_NONE\x10\x00\x12\x1c\n" +
	"\x18LOAD_BALANCE_ROUND_ROBIN\x10\x01\x12\x19\n" +
	"\x15LOAD_BALANCE_URL_HASH\x10\x02\x12\x17\n" +
	"\x13LOAD_BALANCE_RANDOM\x10\x032\xd7\x04\n" +
	"\x17ServiceDiscoveryManager\x120\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x0e.api.PingReply\"\x00\x12<\n" +
	"\tHeartBeat\x12\x15.api.HeartBeatRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\x0fRegisterService\x12\x1b.api.RegisterServiceRequest\x1a\x14.api.GenericResponse\"\x00\x12>\n" +
	"\vAddInstance\x12\x17.api.AddInstanceRequest\x1a\x14.api.GenericResponse\"\x00\x12H\n" +
	"\x11UnregisterService\x12\x1b.api.RegisterServiceRequest\x1a\x14.api.GenericResponse\"\x00\x125\n" +
	"\rDeleteService\x12\f.api.Service\x1a\x14.api.GenericResponse\"\x00\x12B\n" +
	"\rRenameService\x12\x19.api.RenameServiceRequest\x1a\x14.api.GenericResponse\"\x00\x12D\n" +
	"\x0eResolveService\x12\x13.api.ResolveRequest\x1a\x1b.api.ResolveServiceResponse\"\x00\x129\n" +
	"\aMetrics\x12\x16.google.protobuf.Empty\x1a\x14.api.MetricsResponse\"\x00B0Z.github.com/richardbaah/RouteFinder/src/api;apib\x06proto3"

var (
	file_SMD_proto_rawDescOnce sync.Once
	file_SMD_proto_rawDescData []byte
)

func file_SMD_proto_rawDescGZIP() []byte {
	file_SMD_proto_rawDescOnce.Do(func() {
		file_SMD_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SMD_proto_rawDesc), len(file_SMD_proto_rawDesc)))
	})
	return file_SMD_proto_rawDescData
}

var file_SMD_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SMD_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_SMD_proto_goTypes = []any{
	(LoadBalance)(0),                     // 0: api.LoadBalance
	(*HeartBeatRequest)(nil),             // 1: api.HeartBeatRequest
	(*PingReply)(nil),                    // 2: api.PingReply
	(*RegisterServiceRequest)(nil),       // 3: api.RegisterServiceRequest
	(*AddInstanceRequest)(nil),           // 4: api.AddInstanceRequest
	(*GenericResponse)(nil),              // 5: api.GenericResponse
	(*ServiceEndpoint)(nil),              // 6: api.ServiceEndpoint
	(*Service)(nil),                      // 7: api.Service
	(*ResolveServiceResponse)(nil),       // 8: api.ResolveServiceResponse
	(*ResolveRequest)(nil),               // 9: api.ResolveRequest
	(*RenameServiceRequest)(nil),         // 10: api.RenameServiceRequest
	(*MetricsResponse)(nil),              // 11: api.MetricsResponse
	(*MetricsResponseServiceMetric)(nil), // 12: api.MetricsResponse.serviceMetric
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 14: google.protobuf.Empty
}
var file_SMD_proto_depIdxs = []int32{
	13, // 0: api.PingReply.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 1: api.RegisterServiceRequest.endpoints:type_name -> api.ServiceEndpoint
	0,  // 2: api.RegisterServiceRequest.algo:type_name -> api.LoadBalance
	6,  // 3: api.AddInstanceRequest.endpoints:type_name -> api.ServiceEndpoint
	6,  // 4: api.ResolveServiceResponse.endpoints:type_name -> api.ServiceEndpoint
	12, // 5: api.MetricsResponse.services:type_name -> api.MetricsResponse.serviceMetric
	0,  // 6: api.MetricsResponse.serviceMetric.algo:type_name -> api.LoadBalance
	6,  // 7: api.MetricsResponse.serviceMetric.endpoints:type_name -> api.ServiceEndpoint
	14, // 8: api.ServiceDiscoveryManager.Ping:input_type -> google.protobuf.Empty
	1,  // 9: api.ServiceDiscoveryManager.HeartBeat:input_type -> api.HeartBeatRequest
	3,  // 10: api.ServiceDiscoveryManager.RegisterService:input_type -> api.RegisterServiceRequest
	4,  // 11: api.ServiceDiscoveryManager.AddInstance:input_type -> api.AddInstanceRequest
	3,  // 12: api.ServiceDiscoveryManager.UnregisterService:input_type -> api.RegisterServiceRequest
	7,  // 13: api.ServiceDiscoveryManager.DeleteService:input_type -> api.Service
	10, // 14: api.ServiceDiscoveryManager.RenameService:input_type -> api.RenameServiceRequest
	9,  // 15: api.ServiceDiscoveryManager.ResolveService:input_type -> api.ResolveRequest
	14, // 16: api.ServiceDiscoveryManager.Metrics:input_type -> google.protobuf.Empty
	2,  // 17: api.ServiceDiscoveryManager.Ping:output_type -> api.PingReply
	14, // 18: api.ServiceDiscoveryManager.HeartBeat:output_type -> google.protobuf.Empty
	5,  // 19: api.ServiceDiscoveryManager.RegisterService:output_type -> api.GenericResponse
	5,  // 20: api.ServiceDiscoveryManager.AddInstance:output_type -> api.GenericResponse
	5,  // 21: api.ServiceDiscoveryManager.UnregisterService:output_type -> api.GenericResponse
	5,  // 22: api.ServiceDiscoveryManager.DeleteService:output_type -> api.GenericResponse
	5,  // 23: api.ServiceDiscoveryManager.RenameService:output_type -> api.GenericResponse
	8,  // 24: api.ServiceDiscoveryManager.ResolveService:output_type -> api.ResolveServiceResponse
	11, // 25: api.ServiceDiscoveryManager.Metrics:output_type -> api.MetricsResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_SMD_proto_init() }
func file_SMD_proto_init() {
	if File_SMD_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SMD_proto_rawDesc), len(file_SMD_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_SMD_proto_goTypes,
		DependencyIndexes: file_SMD_proto_depIdxs,
		EnumInfos:         file_SMD_proto_enumTypes,
		MessageInfos:      file_SMD_proto_msgTypes,
	}.Build()
	File_SMD_proto = out.File
	file_SMD_proto_goTypes = nil
	file_SMD_proto_depIdxs = nil
}
