// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: SMD.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceDiscoveryManager_Ping_FullMethodName = "/api.ServiceDiscoveryManager/Ping"
)

// ServiceDiscoveryManagerClient is the client API for ServiceDiscoveryManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceDiscoveryManagerClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingReply, error)
}

type serviceDiscoveryManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceDiscoveryManagerClient(cc grpc.ClientConnInterface) ServiceDiscoveryManagerClient {
	return &serviceDiscoveryManagerClient{cc}
}

func (c *serviceDiscoveryManagerClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, ServiceDiscoveryManager_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceDiscoveryManagerServer is the server API for ServiceDiscoveryManager service.
// All implementations must embed UnimplementedServiceDiscoveryManagerServer
// for forward compatibility.
type ServiceDiscoveryManagerServer interface {
	Ping(context.Context, *emptypb.Empty) (*PingReply, error)
	mustEmbedUnimplementedServiceDiscoveryManagerServer()
}

// UnimplementedServiceDiscoveryManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceDiscoveryManagerServer struct{}

func (UnimplementedServiceDiscoveryManagerServer) Ping(context.Context, *emptypb.Empty) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedServiceDiscoveryManagerServer) mustEmbedUnimplementedServiceDiscoveryManagerServer() {
}
func (UnimplementedServiceDiscoveryManagerServer) testEmbeddedByValue() {}

// UnsafeServiceDiscoveryManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceDiscoveryManagerServer will
// result in compilation errors.
type UnsafeServiceDiscoveryManagerServer interface {
	mustEmbedUnimplementedServiceDiscoveryManagerServer()
}

func RegisterServiceDiscoveryManagerServer(s grpc.ServiceRegistrar, srv ServiceDiscoveryManagerServer) {
	// If the following call pancis, it indicates UnimplementedServiceDiscoveryManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceDiscoveryManager_ServiceDesc, srv)
}

func _ServiceDiscoveryManager_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceDiscoveryManagerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceDiscoveryManager_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceDiscoveryManagerServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceDiscoveryManager_ServiceDesc is the grpc.ServiceDesc for ServiceDiscoveryManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceDiscoveryManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ServiceDiscoveryManager",
	HandlerType: (*ServiceDiscoveryManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ServiceDiscoveryManager_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SMD.proto",
}
